### ISSUE TITLE
Add cross-hair for the selected segment?

### ISSUE THREAD

**Issue by fedorov** [QIICR/Reporting#110]
In the situations where multiple segments are visible on the same slice, it might be helpful to unambiguously highlight the region. 

It looks like the easiest way to do this is to enable slice intersections. May not need any changes, or add a shortcut button as in SliceTracker

![image](https://cloud.githubusercontent.com/assets/313942/20580342/cb9c3088-b19f-11e6-84db-be2137b69ee3.png)

**Comment by che85** [comment]
Actually there is a shortcut button in Reporting for displaying a crosshair

![image](https://cloud.githubusercontent.com/assets/10195822/20580395/0b639c24-b1a0-11e6-8982-ffb9590a031d.png)

**Comment by che85** [comment]
But yeah I can add the slicer intersection to it

**Comment by che85** [comment]
@fedorov The crosshair position is not updated while moving the cursor within a view. That's not correct, right?

**Comment by fedorov** [comment]
I think something changed in how crosshairs behave ... not the right time to investigate. I think optimal is just to enable slice intersections. I played with the UI, and it seems to work best.

**Comment by pieper** [comment]
@lassoan did recently change the crosshair behavior - maybe the Reporting code needs to update to match the new behavior?

**Comment by che85** [comment]
@pieper Yes I need to update SlicerProstate then. This is, where I implemented the CrosshairButton.

**Comment by che85** [comment]
I think the behavior is the same....

**Comment by lassoan** [comment]
There were several issues with the crosshair, the most serious is being the crosshair shown in different positions in different slice views (see full list of issues in my commit comment https://github.com/Slicer/Slicer/commit/e1a4a877d8489feeb21fec35c2db0b083a4b728e).
Now you cannot accidentally move the crosshair by moving the mouse over a slice view (you have to keep shift pressed), displayed position is always consistent in all 2D and 3D views (yes, it's shown in 3D views, unlike slice intersections that are directly only shown in slice views), and it's more persistent than slice intersection position (slice intersection position changes immediately when you browse slices; while crosshair position remains).
So, I think crosshair is very appropriate for highlighting a segment position in all viewers and it's useful to jump there with the slices, too. Probably changing slice intersections display is not necessary (let the user decide if he wants to see slice intersections or not).

**Comment by fedorov** [comment]
@lassoan I like the behavior of slice intersection better, in this particular situation. I also have to say I am missing the Navigator mode!

**Comment by lassoan** [comment]
Oh no, really, what was that you could do earlier and cannot do more conveniently now?

**Comment by fedorov** [comment]
@che85 - indeed, after rebuilding SlicerProstate, this issue is resolved - thanks!!

> Oh no, really, what was that you could do earlier and cannot do more conveniently now?
> The navigator mode is still there, but you don't have to hit a tiny box with the mouse but you position the crosshair directly by pressing shift key and positioning the mouse.

@lassoan I know very well about this mode. The problem with this mode is that instead of using just the mouse pointer, I have to remember and use shift. Another problem is that I am not able to keep the crosshairs in place when my mouse needs to go somewhere else.

In the specific situation discussed in this issue, we could have easily used navigator mode to highlight the area, but now we can only do it with slice intersection, since mouse is not in slice viewer - it is in the Segment Editor list.... We can discuss at the project week. For now, I am quite happy with slice intersections. I am in complete agreement with you that buggy behavior had to be fixed, but I don't agree navigator should have been axed.

**Comment by fedorov** [comment]
@lassoan I forgot to mention another reason why the default presence of cross-hair in 3d is super-confusing - when I recenter the view, I don't see anything. My first instinct is - surface generation failed, but the true issue it is out of view because cross-hairs model messes up center calculation.

**Comment by lassoan** [comment]
The crosshair is disabled by default. Do you experience any difference in behavior without explicitly enabling crosshair?

In most data sets, origin (LPS=[0,0,0]) position is "inside", often chosen to be near the point of interest. In what data sets you see the (0,0,0) position far from your data?

I agree that the behavior of "center view" button and "3D cube" is inconsistent if there are distant objects in the scene (center view => centers the field of view on center of the ROI that includes all visible actors; 3D cube: includes displayable nodes, even if invisible). Do you think we should include the crosshair in the "3D cube"?

**Comment by fedorov** [comment]
> The crosshair is disabled by default. Do you experience any difference in behavior without explicitly enabling crosshair?
> 

Yes, I definitely do. Re-centering works as expected when crosshair is not enabled.

> In most data sets, origin (LPS=[0,0,0]) position is "inside", often chosen to be near the point of interest. In what data sets you see the (0,0,0) position far from your data?
> 

Right - unless you deal with the screening scans covering large volumes, such as chest CT or whole body PET/CT. This is exactly what happened in my case - whole body PET scans with the lesions segmented in the head/neck area.

> I agree that the behavior of "center view" button and "3D cube" is inconsistent if there are distant objects in the scene (center view => centers the field of view on center of the ROI that includes all visible actors; 3D cube: includes displayable nodes, even if invisible). Do you think we should include the crosshair in the "3D cube"?

I do think it helps, but I think it should only be enabled when crosshair is activated in 2d view. In this case, the user already "locked" on the target in the slices, and then it does make sense to show it in 3d. When crosshair is not used in slice views, it will be irrelevant in 3d, in addition to breaking functionality of recentering.
