### ISSUE TITLE
Segment anatomic region/modifier is not populated on SEG import

### ISSUE THREAD

**Issue by fedorov** [QIICR/Reporting#111]
This issue was discussed in https://github.com/QIICR/Reporting/issues/107#issuecomment-262632176, and is consistently reproducible with the dataset 2 from this page: https://fedorov.gitbooks.io/rsna2016-qirr-dicom4qi/content/instructions/sr-tid1500.html

It would be good to have it implemented the same way as in http://qiicr.org/dcmqi/#/seg - there is a separate selector for anatomic region context. And then at the time SEG is imported, a dynamic one is created as done for the category/type context. 

@cpinter says:
> 
> Implementing it should be pretty straightforward, I think I can do it tomorrow.
> 
> There is a combobox for anatomic context, and the logic is in place already. Hiding the combobox if there is only one loaded anatomic context is only a feature I added. So adding a new context for the SEG the same way a new terminology context is added will be no problem.

**Comment by cpinter** [comment]
I noticed a discrepancy between the code and the descriptor JSON file. The anatomic region code in the JSON is AnatomicRegionCodeSequence but in the code it's AnatomicRegionSequence. I'll change the code to use AnatomicRegionCodeSequencebut .
My question is about AnatomicRegionModifierSequence, because there is no example for that in this example. Should I also change it to AnatomicRegionModifierCodeSequence in the DICOM plugin?

**Comment by cpinter** [comment]
With the assumption that the word "Code" needs to be in the key, I committed the changes to Slicer core
https://github.com/Slicer/Slicer/commit/2dfc50cb0b9b4265435221267adf162f9b4d7b0f
and updated Reporting in pull request https://github.com/QIICR/Reporting/pull/114

**Comment by fedorov** [comment]
Csaba, it's an inconsistency in dcmqi schema - https://github.com/QIICR/dcmqi/blob/master/doc/seg-schema.json#L136-L141. Indeed, it would be consistent if both AnatomicRegion and AnatomicRegionModifier ended in CodeSequence. 

However, I am reluctant to change this now, since there are multiple other projects that use current version of dcmqi for the RSNA interoperability exhibit. This change would need to propagate to many places in the code. Thanks for #114, but I think I will keep it open for now.

I hope at RSNA there will be an opportunity to agree with the other users of dcmqi on the naming conventions and procedures for code and schema updates.

**Comment by cpinter** [comment]
I'm not sure I understand. As the meta.json files contained data that the DICOM segmentation plugin could not parse, it never worked. So I think if you merge this pull request there will be no noticable change in that manner. At least now the meta.json and the Reporting code would reflect the same convention (which can be changed later, but at least the string search would not be misleading).

**Comment by fedorov** [comment]
Oh, I see - I misunderstood. The problem is at multiple levels. I agree that PR will not hurt. Thanks for explaining!

**Comment by cpinter** [comment]
Great, thanks a lot!

**Comment by fedorov** [comment]
Sorry, just now got to test this. After recompiling Slicer and updating Reporting, I am now getting this error:

```
Traceback (most recent call last):
  File "/Users/fedorov/github/Reporting/Py/Reporting.py", line 231, in onSegmentSelected
    self.segmentEditorWidget.onSegmentSelected(item)
  File "/Users/fedorov/github/Reporting/Py/Reporting.py", line 649, in onSegmentSelected
    self.jumpToSegmentCenter(segment)
  File "/Users/fedorov/github/Reporting/Py/Reporting.py", line 654, in jumpToSegmentCenter
    centroid = self.logic.getSegmentCentroid(self.segmentationNode, segment)
  File "/Users/fedorov/github/Reporting/Py/Reporting.py", line 745, in getSegmentCentroid
    centroid = ModuleLogicMixin.getCentroidForLabel(tempLabel, 1)
  File "/Users/fedorov/local/builds/SlicerProstate/lib/Slicer-4.7/qt-scripted-modules/SlicerProstateUtils/decorators.py", line 130, in __call__
    return function(*args)
  File "/Users/fedorov/local/builds/SlicerProstate/lib/Slicer-4.7/qt-scripted-modules/SlicerProstateUtils/mixins.py", line 375, in getCentroidForLabel
    ls.Execute(labelImage, labelImage)
  File "/Users/fedorov/local/builds/Slicer4-Debug/python-install/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 42601, in Execute
    return _SimpleITK.LabelStatisticsImageFilter_Execute(self, *args)
RuntimeError: Exception thrown in SimpleITK LabelStatisticsImageFilter_Execute: /Users/fedorov/local/builds/Slicer4-Debug/SimpleITK/Code/Common/include/sitkProcessObject.h:277:
sitk::ERROR: Unexpected template dispatch error!
```

**Comment by fedorov** [comment]
I am going to rebuild from scratch

**Comment by fedorov** [comment]
Same runtime error with Slicer built from scratch

**Comment by fedorov** [comment]
Does not happen in the binary! In either case, this specific issue is resolved- I confirm anatomy terminology is initialized in the nightly.

**Comment by cpinter** [comment]
Thank you!
