### ISSUE TITLE
Simplify how python tests access data

### ISSUE THREAD

**Issue by jcfr** [QIICR/Reporting#23]
Assigned this issue to @jcfr 

The idea is to apply the mechanism used [here](https://github.com/Slicer/Slicer/blob/master/Applications/SlicerApp/Testing/Python/slicerappdatapaths.py.in)

**Comment by fedorov** [comment]
@jcfr can you clarify what was the issue, and if you still plan to work on this? The link in "here" is dead ...

**Comment by jcfr** [comment]
Looking at this link works: https://github.com/jcfr/Reporting/commit/3414d8e668f1a012c3694f08e109122e5b6be51e

Just wanted to point a possibly simpler approach to access testing data from within python tests

**Comment by fedorov** [comment]
closing old issue as the extension is being restructured
