### ISSUE TITLE
Use referenced series to populate referenced instances for SEG plugin

### ISSUE THREAD

**Issue by fedorov** [QIICR/Reporting#67]
Currently, only the slices that are referenced are loaded. However, for SEGs it usually makes sense to load all of the slices of the series to which referenced instances belong (those referenced instances may be the full list of series instances, or a subset, which is implementation dependent).

**Comment by pieper** [comment]
At least within Slicer you would almost always load the full series (or at least a portion of it that corresponds to a MRML volume type).  For now it's an error condition of the segmentation doesn't match the referenced geometry.

**Comment by fedorov** [comment]
This specific issue would not address your concern Steve, I was thinking about the feature where user is notified about the referenced series at the time segmentation is loaded. 

I think the right thing to do would be to handle the situation of the incomplete volume in Editor - resample label user is trying to set to the master geometry if mismatch.

Note that the referenced instance sequence is not required when image geometry is communicated in the shared/per-frame functional groups, so it will not be possible in the general case to load SEG as a label that matches the volume of the (unknown) master volume.

**Comment by fedorov** [comment]
The behavior was changed recently in the plugin to load the whole series, since handling selected slices led to geometric issues due to discontinuity introduced when multiple non-overlapping segments were present.
