### ISSUE TITLE
Referenced series is not loaded when loading SEG

### ISSUE THREAD

**Issue by fedorov** [QIICR/Reporting#70]
Looks like this functionality got broken somewhere. More testing needed.

**Comment by pieper** [comment]
Interesting. I tried once and it worked on my local build.

**Comment by fedorov** [comment]
Nevermind, I can't reproduce it, maybe I was using a wrong Slicer instance. Happy Thanksgiving!

**Comment by pieper** [comment]
Happy thanksgiving!
