### ISSUE TITLE
Change of color resets Terminology widget selection

### ISSUE THREAD

**Issue by fedorov** [QIICR/Reporting#77]
If I change color on one segment, and then double click on the color swatch for another one, selection appears to be reset

Tooltip content:

![image](https://cloud.githubusercontent.com/assets/313942/19206342/2de895ec-8cb6-11e6-8767-011737670659.png)

Widget selection:

![image](https://cloud.githubusercontent.com/assets/313942/19206350/3b0b0f66-8cb6-11e6-9865-e91447591fde.png)

(also note color swatch is not synchronized)

**Comment by cpinter** [comment]
I also cannot reproduce this one. Are you absolutely sure you use the latest code?

Last commit is 9577c7a607e0a0d10f5cd9f9d0c78598f991885d with message "Fixed known bugs in terminology selector". I remember fixing something similar than what you described here.

**Comment by cpinter** [comment]
Works completely fine on Mac too. I suspect that the bugfix commit was not rebased on your working copy, because this bug was there before that one.

**Comment by fedorov** [comment]
Thanks for looking into this! Sorry, it looks like it was my fault. I will do a fresh build, test again and update these issues. Probably not today though ...

**Comment by cpinter** [comment]
No worries! I'll leave next Wednesday, so can fix things until then. I consider it a good sign that you didn't find other problems in the first round. There will probably be usability issues later on, but hopefully not too many bugs.

**Comment by fedorov** [comment]
Csaba, to keep things going, does it make sense to start integration into Slicer before you leave, now that the release is cut, or would you like to wait until we do more extensive testing? I think the existing functionality is sufficiently capable to start integration.

**Comment by cpinter** [comment]
No objections on my part, I can start integrating right away.

On October 13, 2016 3:21:45 PM Andrey Fedorov <notifications@github.com> wrote:

Csaba, to keep things going, does it make sense to start integration into Slicer before you leave, now that the release is cut, or would you like to wait until we do more extensive testing? I think the existing functionality is sufficiently capable to start integration.

-

**Comment by cpinter** [comment]
Can this be closed?

**Comment by fedorov** [comment]
Csaba, I was busy with grants for the past 2 weeks, and traveling this week, but I will get back to this soon to test with the latest version, and will close if I cannot reproduce. Sorry for the delay.

**Comment by fedorov** [comment]
This is not happening anymore!
