### ISSUE TITLE
In case of overlapping segments export segments into separate labelmaps and run LabelStatistics for each one

### ISSUE THREAD

**Issue by che85** [QIICR/Reporting#84]

**Comment by fedorov** [comment]
to clarify, do this in the situation when overlapping segments are enabled in the Segmentations GUI

Or perhaps it is easier to calculate statistics consistently for the individual segments all the time?

**Comment by lassoan** [comment]
Segment masking option is a property of the editor, not a property of a segmentation. So, you always have to assume that segments may overlap.

**Comment by che85** [comment]
outdated
