### ISSUE TITLE
Enable readonly mode for measurement reports

### ISSUE THREAD

**Issue by che85** [QIICR/Reporting#90]
After loading a DICOM SR into Slicer it shall be available for selection in Reporting. 

This is also applicable to completed measurement reports.

Once selected, it should be read only:

- [x] Disable SegmentEditor
  - [x] No adding/removing of segments (@che85)
  - [x] Selection of segments should be possible, but not editable (@cpinter)
    - [x] No changes of segment name or terminology 
- [x] Reporting Buttons shall be disabled (@che85)

@fedorov Feel free to add items or change this list
@cpinter Is it possible to disable double click event listeners for segment name and terminology widget? Or at least forbid the change somehow?

**Comment by fedorov** [comment]
@che85 thanks for setting up the milestone, and also for summarizing these points. This looks good. I think given the time left, we should not allow editing reports loaded from DICOM, and just complete the round-trip.

**Comment by fedorov** [comment]
> @cpinter Is it possible to disable double click event listeners for segment name and terminology widget? Or at least forbid the change somehow?

@cpinter can you answer Christian's question?

**Comment by che85** [comment]
@cpinter I propose to add a flag "readonly" or something similar for the vtkSegmentationNode. Is this the case, the SegmentEditor should disable the following:

- [ ] Add/Remove segment
- [ ] Create surface
- [ ] Terminology selection should be disabled (maybe allow dblclick on the color icon and open the terminology dialog, but forbid changing it) - otherwise the user wouldn't have the chance to check the terminology? 
- [ ] Forbid changing the name of segments

Very important is, that the segments can still be selected, so that we can jump to the center of the segment when it's clicked.

**Comment by fedorov** [comment]
> (maybe allow dblclick on the color icon and open the terminology dialog, but forbid changing it) - otherwise the user wouldn't have the chance to check the terminology?

@che85 the user can check terminology in the tooltip over the color swatch. It is suboptimal, but better than nothing.

**Comment by che85** [comment]
Oh I thought about that, but I didn't even try .... I will update the comment and make that optional

**Comment by cpinter** [comment]
It shouldn't be hard to add a reado-only option. I'd prefer adding that option to the segments table and not the nodes, unless it is important that some nodes be read-only and not others.

**Comment by che85** [comment]
@cpinter Sounds great.

**Comment by lassoan** [comment]
Read-only widgets should be no problem, but restricting modules is more difficult and also uncommon in Slicer. What is the reason of locking? Preventing accidental changes? (as it is the case for markups when drag-and-dropping with the mouse may accidentally displace a markup)
Can we just hide the nodes so that they are only shown in selected modules that don't allow modifications?

**Comment by che85** [comment]
@lassoan We are not showing the SegmentationNode at all. Loading the DICOM SR into Slicer creates a vtkMRMLTableNode, which references the SegmentationNode.

There is no SegmentationNodeSelector in our "Reporting" module. So just hiding the node wouldn't help us.

Reason for readonly: Currently we only want to support creation and reading of DICOM SR. Modification should not be allowed. That's why we only load the DICOM SR into Slicer with the segmentation for only displaying the results int "Reporting" with avoiding any modifications.

Of course, if the user knows how to modify it by using another module, we cannot avoid that...

**Comment by lassoan** [comment]
Very good then. Making widgets read-only should be straightforward to implement.

**Comment by fedorov** [comment]
Good plan, thanks!

The reason for read-only for SRs is not just limitations of the scope of our implementation. There are real use cases where this is an important feature.

**Comment by cpinter** [comment]
Commit https://github.com/Slicer/Slicer/commit/b654947774b2ee02b80c118391023c6b4e379131 adds read-only to segment editor and segments table view. Please close if satisfactory
