### ISSUE TITLE
Upon measurement report selection referenced scalar volume should be displayed next to segmentation

### ISSUE THREAD

**Issue by che85** [QIICR/Reporting#94]

**Comment by fedorov** [comment]
I am not sure I understand - it is already displayed right under the report selector, no? Can you clarify?

![image](https://cloud.githubusercontent.com/assets/313942/20446829/8949a57a-ada9-11e6-8869-a5bf3ea0735e.png)

**Comment by che85** [comment]
Yes I meant to say, that if there is no measurement report selected and the user selects one, Reporting needs to make sure, that the right images are displayed in the slice views

**Comment by che85** [comment]
Already implemented
