### ISSUE TITLE
Slicer crashes after selection terminology category in Segment Editor

### ISSUE THREAD

**Issue by che85** [QIICR/Reporting#98]
Slicer nightly build 4.7.0-2016-11-21 crashes after selection of terminology. Report [1]

Reproduce:
1. Load scalar volume into Slicer
2. Open Segment Editor
3. Add Segment
4. DblClick on color icon for selection of terminology
5. Select Category without selection of Property Type
6. Click button "Select"
7. DblClick on color icon for selection of terminology for the same segment
8. Slicer crashes....

[1] https://gist.github.com/che85/2f1cdf90d621895ec7718ee65409fbc8

**Comment by cpinter** [comment]
I'll look into this right now.
Thanks for testing!

**Comment by che85** [comment]
Sure :)

**Comment by cpinter** [comment]
I'll fix the crash anyway, but maybe Select button should be disabled until type is selected. It doesn't make much sense to allow the user to select only a category

**Comment by che85** [comment]
Yes I agree
