### ISSUE TITLE
Creation of DICOM SR doesn't work due to changes in Slicer Core

### ISSUE THREAD

**Issue by che85** [QIICR/Reporting#99]
Changes has been made in [1] 
Code that used getters doesn't work anymore [2]

[1] https://github.com/Slicer/Slicer/commit/62431b3dcb74c2f6f0bb5871c3130d8895451eda#diff-59ab6f6918e7ad77de78006802f56b17R44
[2] https://github.com/QIICR/Reporting/blob/master/Py/Reporting.py#L794-L795

@cpinter Do you have some hints for me? It seems, like a lot has been changed in that commit

**Comment by che85** [comment]
@pinter: Seems like I have to use 

```
segment.GetTag(segment.GetTerminologyEntryTagName(), value)
```

and then split the string?

**Comment by cpinter** [comment]
What is your goal?

You can deserialize the string into a VTK object by calling qSlicerTerminologyNavigatorWidget::deserializeTerminologyEntry, then you can access the details from the vtkSlicerTerminologyEntry object. The object will contain all the fields, not just the identifiers if it's found in a loaded terminology dictionary.

**Comment by che85** [comment]
How do I do that from python? I need to add the terminology to our metafile in order to create the DICOM SEG and DICOM SR.

**Comment by che85** [comment]
Ok seems like i found it

**Comment by cpinter** [comment]
It's a static function but unfortunately calling static functions somehow doesn't work from python (it used to). So you need to do
terminologyWidget = slicer.qSlicerTerminologyNavigatorWidget()
terminologyEntry = slicer.vtkSlicerTerminologyEntry()
terminologyWidget.deserializeTerminologyEntry(tag, terminologyEntry)

**Comment by che85** [comment]
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: qSlicerTerminologyNavigatorWidget has no attribute named 'deserializeTerminologyEntry'
```

**Comment by cpinter** [comment]
Interesting. Maybe it just needs a Q_INVOKABLE. Will let you know in a sec

**Comment by che85** [comment]
It's also interesting that I can access serializeTerminologyEntry

**Comment by cpinter** [comment]
It has the Q_INVOKABLE :)

**Comment by cpinter** [comment]
I committed the change to Slicer trunk
Sorry for the oversight!

**Comment by che85** [comment]
Ok thanks a lot :)
